---
- name: Check if VM already exists
  ansible.builtin.command: "qm status {{ haos_vmid }}"
  register: proxmox_haos_vm_status
  failed_when: false
  changed_when: false

- name: Create HAOS VM skeleton
  ansible.builtin.command: >
    qm create {{ haos_vmid }}
    --name {{ haos_vm_name }}
    --memory {{ haos_memory }}
    --cores {{ haos_cores }}
    --net0 virtio,bridge={{ haos_bridge }}
    --machine q35
    --bios ovmf
  when: proxmox_haos_vm_status.rc != 0
  changed_when: true

- name: Import HAOS Disk to Storage
  ansible.builtin.command: >
    qm importdisk {{ haos_vmid }}
    /var/lib/vz/template/cache/haos_ova-{{ haos_version }}.qcow2
    {{ haos_storage }}
    --format qcow2
  when: proxmox_haos_vm_status.rc != 0
  changed_when: true
  notify:
    - Configure Boot Order
    - Start VM

- name: Flush handlers to ensure VM is ready for summary
  ansible.builtin.meta: flush_handlers
